### ISSUE TITLE
Skip newest items, not oldest

### ISSUE THREAD

**Issue by Webstylerin** [inspiredminds/contao-eventlist-extended#1]
I try to split my eventlist to show the newest 10 events immediatly and to show the rest in an accordion.

The first module with "Number of events" works fine, but the second with "Skip items" set to 10 skips the oldest events, not the newest. I tried "-10", but that's no natural number. :)

Is there a way to change on which end the events are skipped?

Regards, Nicole

**Comment by fritzmg** [comment]
Hm, yeah the current implementation only works one way and not the other. It's not taking the sorting setting of the module into account.

**Comment by fritzmg** [comment]
Fixed in `1.2.2`.
